#!/bin/bash

# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix

export LOCALE_ARCHIVE_2_27="$HOME/.local/share/nix-locale/result/lib/locale/locale-archive"
export LOCALE_ARCHIVE_2_11="/usr/lib/locale/locale-archive"

export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PATH="$HOME/localbin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
