if [ -f ~/.localrc.before ]; then
    . ~/.localrc.before
fi

source ~/.zsh/aliases
source ~/.zsh/autojump
source ~/.zsh/completion
source ~/.zsh/config
source ~/.zsh/path
source ~/.zsh/prompt
source ~/.zsh/fzf
source ~/.zsh/direnv
source ~/.zsh/node

if [ -f ~/.localrc ]; then
    . ~/.localrc
fi

# added by travis gem
[ -f /home/carl/.travis/travis.sh ] && source /home/carl/.travis/travis.sh
