if [ -f ${HOME}/.localrc.before ]; then
    source ${HOME}/.localrc.before
fi

if [[ ${PROFILE_ZSH:0} -eq 1 ]]; then zmodload zsh/zprof; fi

export ZSH_HOME="${HOME}/.zsh"

source "${ZSH_HOME}/antigen.zsh"
antigen init "${ZSH_HOME}/antigenrc.zsh"

if [ -f ${HOME}/.localrc ]; then
    source ${HOME}/.localrc
fi

if [[ ${PROFILE_ZSH} -eq 1 ]]; then zprof; fi
