source ~/.zsh/aliases
source ~/.zsh/completion
source ~/.zsh/config
source ~/.zsh/path
source ~/.zsh/prompt
source ~/.zsh/fasd
source ~/.zsh/fzf
source ~/.zsh/direnv
source ~/.zsh/node
source ~/.zsh/bw

if [ -f ~/.localrc ]; then
    . ~/.localrc
fi
