#!/bin/bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# startup scripts
xsetroot -solid '#262626'
autorandr -cf

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod1    # Use alt as the main modifier

hc keybind $Mod-Shift-q close
hc keybind $Mod-Shift-r reload
hc keybind $Mod-space spawn rofi -show run
hc keybind $Mod-Return spawn alacritty

# audio
hc keybind XF86AudioRaiseVolume spawn amixer -q sset Master 5%+ unmute
hc keybind XF86AudioLowerVolume spawn amixer -q sset Master 5%- unmute
hc keybind XF86AudioMute spawn amixer -q sset Master toggle

# display
hc keybind $Mod-F7 spawn autorandr -cf
hc keybind XF86MonBrightnessUp spawn xbacklight +15
hc keybind XF86MonBrightnessDown spawn xbacklight -15

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
hc keybind $Mod-d chain , split right , focus -e r
hc keybind $Mod-Shift-d chain , split bottom , focus -e d

# explode the current frame
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc set swap_monitors_to_get_tag 0

# layouting
hc keybind $Mod-z spawn select-layout
hc keybind $Mod-x remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-space set_attr clients.focus.floating toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-c cycle_layout 1 vertical horizontal

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#585987'
hc set frame_border_width 1
hc set frame_bg_transparent on
hc set frame_transparent_width 4

hc set always_show_frame false
hc set frame_gap 4
hc set frame_padding 0
hc set window_gap 0

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color '#ffa500'
hc attr theme.inner_width 2
hc attr theme.inner_color black
hc attr theme.border_width 4
hc attr theme.floating.border_width 5
hc attr theme.floating.outer_width 2
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#9fbc00'
hc attr theme.background_color '#2b2d31'

hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0

# rules
hc unrule -F

# focus new clients
hc rule focus=on
# try to place floats non-overlapping by default
hc rule floatplacement=smart

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# always float certain apps
hc rule class=Pavucontrol floating=on floatplacement=center
hc rule class=Blueman-manager floating=on floatplacement=center

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# load monitors
hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done
