#!/usr/bin/env bash
set -e

OS="$(uname)"

ROOTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# bring in helper functions
source $ROOTDIR/lib.sh

# install common dotfiles
install_dotfile ctags
install_dotfile gitconfig
install_dotfile gitignore
install_dotfile ideavimrc
install_dotfile ripgreprc
install_dotfile taskrc
install_dotfile vimrc_basic
install_dotfile zsh
install_dotfile zshrc
mkdir -p .config/nvim/swp
install_dotfile init.vim .config/nvim/init.vim
install_dotfile coc-settings.json .config/nvim/coc-settings.json

# install linux specific dotfiles
if [[ "${OS}" != "Darwin" ]] ; then
    install_dotfile npmrc
    install_dotfile Xresources
    install_dotfile autorandr
    install_dotfile compton.conf
    install_dotfile dunst .config/dunst
    install_dotfile i3 .config/i3
    install_dotfile i3blocks .config/i3blocks
    install_dotfile alacritty .config/alacritty
fi

# link this repo into home as .config/nixpkgs
safelink "$HOME/.config/nixpkgs" "$ROOTDIR"
mkdir -p "$HOME/.nixpkgs"
safelink "$HOME/.nixpkgs/config.nix" "$ROOTDIR/config.nix"

if [[ "${OS}" != "Darwin" ]] ; then
    # add a link to bin
    safelink "$HOME/bin" "$ROOTDIR/bin"
fi
