# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "motion-${version}";
  version = "20160410-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "efb4eef465f585649e0a89636e2f2bd6f543482d";

  goPackagePath = "github.com/fatih/motion";
  subPackages = [ "." ];

  src = fetchgit {
    inherit rev;
    url = "https://github.com/fatih/motion";
    sha256 = "0yay4a1b5l9f4zmwkcsmr5plnp7a9b66bczy1xz4nzhl20bal6sx";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
