# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "impl-${version}";
  version = "20160520-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "43306ba79c4e3d1a038db0365b189ad4cca413c6";

  goPackagePath = "github.com/josharian/impl";
  subPackages = [ "." ];

  src = fetchgit {
    inherit rev;
    url = "https://github.com/josharian/impl";
    sha256 = "0l8pq3w0cpc4vs21axaz30qgp0yi5ny3sxja5qh64pwqlbcc1sp5";
  };

  goDeps = ./deps.nix;
}
