#!/bin/bash

CONFIG="$HOME/.config/alacritty/alacritty.yml"
CURRENT=$(awk '/colors: \*/ {gsub(/\*/,"",$2); print $2}' "${CONFIG}")

if [[ "${CURRENT}" == 'light' ]]; then
    echo "  "
    echo "  "
    echo
else
    echo "  "
    echo "  "
    echo
fi
