# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "gogetdoc-${version}";
  version = "20161004-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "54e15dfc8cfdb34d9c674721999d302286e85e62";

  goPackagePath = "github.com/zmb3/gogetdoc";
  subPackages = [ "." ];

  src = fetchgit {
    inherit rev;
    url = "https://github.com/zmb3/gogetdoc";
    sha256 = "0m726y9vw24b682yg7h60zg2aw5yika3kd2c6n67ankhsk2j624i";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
