# This file was generated by go2nix.
[
  {
    goPackagePath = "golang.org/x/tools";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/tools";
      rev = "167995c67fa45f3a7fc8dab62bb872212e397c11";
      sha256 = "048gvp6vw8q2v2xi3d3qakwd9jzm1hd313lm6wkq8195k54l2ddz";
    };
  }
]
