# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "asmfmt-${version}";
  version = "20160829-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "39a37c8aed8095e0fdfb07f78fc8acbd465d9627";

  goPackagePath = "github.com/klauspost/asmfmt";
  subPackages = [ "cmd/asmfmt" ];

  src = fetchgit {
    inherit rev;
    url = "https://github.com/klauspost/asmfmt";
    sha256 = "0a2pkm5glqr1rx3f380f543fjdmj5945nvfiqd5angddp7f0g8iv";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
