# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "errcheck-${version}";
  version = "20161118-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "db0ca22445717d1b2c51ac1034440e0a2a2de645";

  goPackagePath = "github.com/kisielk/errcheck";
  subPackages = [ "." ];

  src = fetchgit {
    inherit rev;
    url = "https://github.com/kisielk/errcheck";
    sha256 = "1q2vy71r7wq1hyr3wr7w6i5w8v27armi9aa6m33nv4zbzcwkskzb";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
