# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "errcheck-${version}";
  version = "20160706-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "aa69c6199800e8aeeedf51950f830458e4cb73e3";

  goPackagePath = "github.com/kisielk/errcheck";
  subPackages = [ "." ];

  src = fetchgit {
    inherit rev;
    url = "https://github.com/kisielk/errcheck";
    sha256 = "164g111vx5q723y0y9sfvdh1czyhggv16lhgajxzgqlwah435klp";
  };

  goDeps = ./deps.nix;
}
