# This file was generated by go2nix.
[
  {
    goPackagePath = "github.com/kisielk/gotool";
    fetch = {
      type = "git";
      url = "https://github.com/kisielk/gotool";
      rev = "5e136deb9b893bbe6c8f23236ff4378b7a8a0dbb";
      sha256 = "1ackx78d5isbxpywfz8ykk4kfsk8yl12wahmm5ivs3spifb8bd3g";
    };
  }
  {
    goPackagePath = "golang.org/x/tools";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/tools";
      rev = "167995c67fa45f3a7fc8dab62bb872212e397c11";
      sha256 = "048gvp6vw8q2v2xi3d3qakwd9jzm1hd313lm6wkq8195k54l2ddz";
    };
  }
]
