# This file has been generated by node2nix 1.0.0. Do not edit!

{nodeEnv, fetchurl, fetchgit}:

let
  sources = {
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "concat-stream-1.5.1" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.5.1.tgz";
        sha1 = "f3b80acf9e1f48e3875c0688b41b6c31602eea1c";
      };
    };
    "debug-2.2.0" = {
      name = "debug";
      packageName = "debug";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.2.0.tgz";
        sha1 = "f87057e995b1a1f6ae6a4960664137bc56f039da";
      };
    };
    "doctrine-1.3.0" = {
      name = "doctrine";
      packageName = "doctrine";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/doctrine/-/doctrine-1.3.0.tgz";
        sha1 = "13e75682b55518424276f7c173783456ef913d26";
      };
    };
    "escope-3.6.0" = {
      name = "escope";
      packageName = "escope";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escope/-/escope-3.6.0.tgz";
        sha1 = "e01975e812781a163a6dadfdd80398dc64c889c3";
      };
    };
    "espree-3.1.7" = {
      name = "espree";
      packageName = "espree";
      version = "3.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/espree/-/espree-3.1.7.tgz";
        sha1 = "fd5deec76a97a5120a9cd3a7cb1177a0923b11d2";
      };
    };
    "estraverse-4.2.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-4.2.0.tgz";
        sha1 = "0dee3fed31fcd469618ce7342099fc1afa0bdb13";
      };
    };
    "esutils-2.0.2" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.2.tgz";
        sha1 = "0abf4f1caa5bcb1f7a9d8acc6dea4faaa04bac9b";
      };
    };
    "file-entry-cache-2.0.0" = {
      name = "file-entry-cache";
      packageName = "file-entry-cache";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-entry-cache/-/file-entry-cache-2.0.0.tgz";
        sha1 = "c392990c3e684783d838b8c84a45d8a048458361";
      };
    };
    "glob-7.0.6" = {
      name = "glob";
      packageName = "glob";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.0.6.tgz";
        sha1 = "211bafaf49e525b8cd93260d14ab136152b3f57a";
      };
    };
    "globals-9.9.0" = {
      name = "globals";
      packageName = "globals";
      version = "9.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globals/-/globals-9.9.0.tgz";
        sha1 = "4c5ffc359fb21edc83fedb87b1c0b414dc24d552";
      };
    };
    "ignore-3.1.5" = {
      name = "ignore";
      packageName = "ignore";
      version = "3.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ignore/-/ignore-3.1.5.tgz";
        sha1 = "54ba1eb92ef9fff8d49e5a1fb23961cdba77eb7a";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha1 = "9218b9b2b928a238b13dc4fb6b6d576f231453ea";
      };
    };
    "inquirer-0.12.0" = {
      name = "inquirer";
      packageName = "inquirer";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/inquirer/-/inquirer-0.12.0.tgz";
        sha1 = "1ef2bfd63504df0bc75785fff8c2c41df12f077e";
      };
    };
    "is-my-json-valid-2.13.1" = {
      name = "is-my-json-valid";
      packageName = "is-my-json-valid";
      version = "2.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-my-json-valid/-/is-my-json-valid-2.13.1.tgz";
        sha1 = "d55778a82feb6b0963ff4be111d5d1684e890707";
      };
    };
    "is-resolvable-1.0.0" = {
      name = "is-resolvable";
      packageName = "is-resolvable";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-resolvable/-/is-resolvable-1.0.0.tgz";
        sha1 = "8df57c61ea2e3c501408d100fb013cf8d6e0cc62";
      };
    };
    "js-yaml-3.6.1" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.6.1.tgz";
        sha1 = "6e5fe67d8b205ce4d22fad05b7781e8dadcc4b30";
      };
    };
    "json-stable-stringify-1.0.1" = {
      name = "json-stable-stringify";
      packageName = "json-stable-stringify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify/-/json-stable-stringify-1.0.1.tgz";
        sha1 = "9a759d39c5f2ff503fd5300646ed445f88c4f9af";
      };
    };
    "levn-0.3.0" = {
      name = "levn";
      packageName = "levn";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.3.0.tgz";
        sha1 = "3b09924edf9f083c0490fdd4c0bc4421e04764ee";
      };
    };
    "lodash-4.15.0" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.15.0.tgz";
        sha1 = "3162391d8f0140aa22cf8f6b3c34d6b7f63d3aa9";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "natural-compare-1.4.0" = {
      name = "natural-compare";
      packageName = "natural-compare";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/natural-compare/-/natural-compare-1.4.0.tgz";
        sha1 = "4abebfeed7541f2c27acfb29bdbbd15c8d5ba4f7";
      };
    };
    "optionator-0.8.1" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.8.1.tgz";
        sha1 = "e31b4932cdd5fb862a8b0d10bc63d3ee1ec7d78b";
      };
    };
    "path-is-inside-1.0.1" = {
      name = "path-is-inside";
      packageName = "path-is-inside";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-inside/-/path-is-inside-1.0.1.tgz";
        sha1 = "98d8f1d030bf04bd7aeee4a1ba5485d40318fd89";
      };
    };
    "pluralize-1.2.1" = {
      name = "pluralize";
      packageName = "pluralize";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pluralize/-/pluralize-1.2.1.tgz";
        sha1 = "d1a21483fd22bb41e58a12fa3421823140897c45";
      };
    };
    "progress-1.1.8" = {
      name = "progress";
      packageName = "progress";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/progress/-/progress-1.1.8.tgz";
        sha1 = "e260c78f6161cdd9b0e56cc3e0a85de17c7a57be";
      };
    };
    "require-uncached-1.0.2" = {
      name = "require-uncached";
      packageName = "require-uncached";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-uncached/-/require-uncached-1.0.2.tgz";
        sha1 = "67dad3b733089e77030124678a459589faf6a7ec";
      };
    };
    "shelljs-0.6.1" = {
      name = "shelljs";
      packageName = "shelljs";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/shelljs/-/shelljs-0.6.1.tgz";
        sha1 = "ec6211bed1920442088fe0f70b2837232ed2c8a8";
      };
    };
    "strip-bom-3.0.0" = {
      name = "strip-bom";
      packageName = "strip-bom";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-bom/-/strip-bom-3.0.0.tgz";
        sha1 = "2334c18e9c759f7bdd56fdef7e9ae3d588e68ed3";
      };
    };
    "strip-json-comments-1.0.4" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-1.0.4.tgz";
        sha1 = "1e15fbcac97d3ee99bf2d73b4c656b082bbafb91";
      };
    };
    "table-3.7.8" = {
      name = "table";
      packageName = "table";
      version = "3.7.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/table/-/table-3.7.8.tgz";
        sha1 = "b424433ef596851922b2fd77224a69a1951618eb";
      };
    };
    "text-table-0.2.0" = {
      name = "text-table";
      packageName = "text-table";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/text-table/-/text-table-0.2.0.tgz";
        sha1 = "7f5ee823ae805207c00af2df4a84ec3fcfa570b4";
      };
    };
    "user-home-2.0.0" = {
      name = "user-home";
      packageName = "user-home";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/user-home/-/user-home-2.0.0.tgz";
        sha1 = "9c70bfd8169bc1dcbf48604e0f04b8b49cde9e9f";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "ansi-regex-2.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.0.0.tgz";
        sha1 = "c5061b6e0ef8a81775e50f5d66151bf6bf371107";
      };
    };
    "inherits-2.0.1" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz";
        sha1 = "b17d08d326b4423e568eff719f91b0b1cbdf69f1";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "readable-stream-2.0.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.6.tgz";
        sha1 = "8f90341e68a53ccc928788dacfcd11b36eb9b78e";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "ms-0.7.1" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.1.tgz";
        sha1 = "9cd13c03adbff25b65effde7ce864ee952017098";
      };
    };
    "es6-map-0.1.4" = {
      name = "es6-map";
      packageName = "es6-map";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-map/-/es6-map-0.1.4.tgz";
        sha1 = "a34b147be224773a4d7da8072794cefa3632b897";
      };
    };
    "es6-weak-map-2.0.1" = {
      name = "es6-weak-map";
      packageName = "es6-weak-map";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-weak-map/-/es6-weak-map-2.0.1.tgz";
        sha1 = "0d2bbd8827eb5fb4ba8f97fbfea50d43db21ea81";
      };
    };
    "esrecurse-4.1.0" = {
      name = "esrecurse";
      packageName = "esrecurse";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esrecurse/-/esrecurse-4.1.0.tgz";
        sha1 = "4713b6536adf7f2ac4f327d559e7756bff648220";
      };
    };
    "d-0.1.1" = {
      name = "d";
      packageName = "d";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d/-/d-0.1.1.tgz";
        sha1 = "da184c535d18d8ee7ba2aa229b914009fae11309";
      };
    };
    "es5-ext-0.10.12" = {
      name = "es5-ext";
      packageName = "es5-ext";
      version = "0.10.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/es5-ext/-/es5-ext-0.10.12.tgz";
        sha1 = "aa84641d4db76b62abba5e45fd805ecbab140047";
      };
    };
    "es6-iterator-2.0.0" = {
      name = "es6-iterator";
      packageName = "es6-iterator";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-iterator/-/es6-iterator-2.0.0.tgz";
        sha1 = "bd968567d61635e33c0b80727613c9cb4b096bac";
      };
    };
    "es6-set-0.1.4" = {
      name = "es6-set";
      packageName = "es6-set";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-set/-/es6-set-0.1.4.tgz";
        sha1 = "9516b6761c2964b92ff479456233a247dc707ce8";
      };
    };
    "es6-symbol-3.1.0" = {
      name = "es6-symbol";
      packageName = "es6-symbol";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-symbol/-/es6-symbol-3.1.0.tgz";
        sha1 = "94481c655e7a7cad82eba832d97d5433496d7ffa";
      };
    };
    "event-emitter-0.3.4" = {
      name = "event-emitter";
      packageName = "event-emitter";
      version = "0.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-emitter/-/event-emitter-0.3.4.tgz";
        sha1 = "8d63ddfb4cfe1fae3b32ca265c4c720222080bb5";
      };
    };
    "estraverse-4.1.1" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-4.1.1.tgz";
        sha1 = "f6caca728933a850ef90661d0e17982ba47111a2";
      };
    };
    "object-assign-4.1.0" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.0.tgz";
        sha1 = "7a3b3d0e98063d43f4c03f2e8ae6cd51a86883a0";
      };
    };
    "acorn-3.3.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-3.3.0.tgz";
        sha1 = "45e37fb39e8da3f25baee3ff5369e2bb5f22017a";
      };
    };
    "acorn-jsx-3.0.1" = {
      name = "acorn-jsx";
      packageName = "acorn-jsx";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-jsx/-/acorn-jsx-3.0.1.tgz";
        sha1 = "afdf9488fb1ecefc8348f6fb22f464e32a58b36b";
      };
    };
    "flat-cache-1.2.1" = {
      name = "flat-cache";
      packageName = "flat-cache";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/flat-cache/-/flat-cache-1.2.1.tgz";
        sha1 = "6c837d6225a7de5659323740b36d5361f71691ff";
      };
    };
    "circular-json-0.3.1" = {
      name = "circular-json";
      packageName = "circular-json";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/circular-json/-/circular-json-0.3.1.tgz";
        sha1 = "be8b36aefccde8b3ca7aa2d6afc07a37242c0d2d";
      };
    };
    "del-2.2.2" = {
      name = "del";
      packageName = "del";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/del/-/del-2.2.2.tgz";
        sha1 = "c12c981d067846c84bcaf862cff930d907ffd1a8";
      };
    };
    "graceful-fs-4.1.6" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.6.tgz";
        sha1 = "514c38772b31bee2e08bedc21a0aeb3abf54c19e";
      };
    };
    "write-0.2.1" = {
      name = "write";
      packageName = "write";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/write/-/write-0.2.1.tgz";
        sha1 = "5fc03828e264cea3fe91455476f7a3c566cb0757";
      };
    };
    "globby-5.0.0" = {
      name = "globby";
      packageName = "globby";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globby/-/globby-5.0.0.tgz";
        sha1 = "ebd84667ca0dbb330b99bcfc68eac2bc54370e0d";
      };
    };
    "is-path-cwd-1.0.0" = {
      name = "is-path-cwd";
      packageName = "is-path-cwd";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-path-cwd/-/is-path-cwd-1.0.0.tgz";
        sha1 = "d225ec23132e89edd38fda767472e62e65f1106d";
      };
    };
    "is-path-in-cwd-1.0.0" = {
      name = "is-path-in-cwd";
      packageName = "is-path-in-cwd";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-path-in-cwd/-/is-path-in-cwd-1.0.0.tgz";
        sha1 = "6477582b8214d602346094567003be8a9eac04dc";
      };
    };
    "pify-2.3.0" = {
      name = "pify";
      packageName = "pify";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-2.3.0.tgz";
        sha1 = "ed141a6ac043a849ea588498e7dca8b15330e90c";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "rimraf-2.5.4" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.5.4.tgz";
        sha1 = "96800093cbf1a0c86bd95b4625467535c29dfa04";
      };
    };
    "array-union-1.0.2" = {
      name = "array-union";
      packageName = "array-union";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-union/-/array-union-1.0.2.tgz";
        sha1 = "9a34410e4f4e3da23dea375be5be70f24778ec39";
      };
    };
    "arrify-1.0.1" = {
      name = "arrify";
      packageName = "arrify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/arrify/-/arrify-1.0.1.tgz";
        sha1 = "898508da2226f380df904728456849c1501a4b0d";
      };
    };
    "array-uniq-1.0.3" = {
      name = "array-uniq";
      packageName = "array-uniq";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-uniq/-/array-uniq-1.0.3.tgz";
        sha1 = "af6ac877a25cc7f74e058894753858dfdb24fdb6";
      };
    };
    "is-path-inside-1.0.0" = {
      name = "is-path-inside";
      packageName = "is-path-inside";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-path-inside/-/is-path-inside-1.0.0.tgz";
        sha1 = "fc06e5a1683fbda13de667aff717bbc10a48f37f";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "inflight-1.0.5" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.5.tgz";
        sha1 = "db3204cd5a9de2e6cd890b85c6e2f66bcf4f620a";
      };
    };
    "minimatch-3.0.3" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.3.tgz";
        sha1 = "2a4e4090b96b2db06a9d7df01055a62a77c9b774";
      };
    };
    "once-1.3.3" = {
      name = "once";
      packageName = "once";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.3.3.tgz";
        sha1 = "b2e261557ce4c314ec8304f3fa82663e4297ca20";
      };
    };
    "path-is-absolute-1.0.0" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.0.tgz";
        sha1 = "263dada66ab3f2fb10bf7f9d24dd8f3e570ef912";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "brace-expansion-1.1.6" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.6.tgz";
        sha1 = "7197d7eaa9b87e648390ea61fc66c84427420df9";
      };
    };
    "balanced-match-0.4.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-0.4.2.tgz";
        sha1 = "cb3f3e3c732dc0f01ee70b403f302e61d7709838";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "ansi-escapes-1.4.0" = {
      name = "ansi-escapes";
      packageName = "ansi-escapes";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-1.4.0.tgz";
        sha1 = "d3a8a83b319aa67793662b13e761c7911422306e";
      };
    };
    "cli-cursor-1.0.2" = {
      name = "cli-cursor";
      packageName = "cli-cursor";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-cursor/-/cli-cursor-1.0.2.tgz";
        sha1 = "64da3f7d56a54412e59794bd62dc35295e8f2987";
      };
    };
    "cli-width-2.1.0" = {
      name = "cli-width";
      packageName = "cli-width";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-width/-/cli-width-2.1.0.tgz";
        sha1 = "b234ca209b29ef66fc518d9b98d5847b00edf00a";
      };
    };
    "figures-1.7.0" = {
      name = "figures";
      packageName = "figures";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/figures/-/figures-1.7.0.tgz";
        sha1 = "cbe1e3affcf1cd44b80cadfed28dc793a9701d2e";
      };
    };
    "readline2-1.0.1" = {
      name = "readline2";
      packageName = "readline2";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/readline2/-/readline2-1.0.1.tgz";
        sha1 = "41059608ffc154757b715d9989d199ffbf372e35";
      };
    };
    "run-async-0.1.0" = {
      name = "run-async";
      packageName = "run-async";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-async/-/run-async-0.1.0.tgz";
        sha1 = "c8ad4a5e110661e402a7d21b530e009f25f8e389";
      };
    };
    "rx-lite-3.1.2" = {
      name = "rx-lite";
      packageName = "rx-lite";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rx-lite/-/rx-lite-3.1.2.tgz";
        sha1 = "19ce502ca572665f3b647b10939f97fd1615f102";
      };
    };
    "string-width-1.0.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz";
        sha1 = "118bdf5b8cdc51a2a7e70d211e07e2b0b9b107d3";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "restore-cursor-1.0.1" = {
      name = "restore-cursor";
      packageName = "restore-cursor";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/restore-cursor/-/restore-cursor-1.0.1.tgz";
        sha1 = "34661f46886327fed2991479152252df92daa541";
      };
    };
    "exit-hook-1.1.1" = {
      name = "exit-hook";
      packageName = "exit-hook";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/exit-hook/-/exit-hook-1.1.1.tgz";
        sha1 = "f05ca233b48c05d54fff07765df8507e95c02ff8";
      };
    };
    "onetime-1.1.0" = {
      name = "onetime";
      packageName = "onetime";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-1.1.0.tgz";
        sha1 = "a1f7838f8314c516f05ecefcbc4ccfe04b4ed789";
      };
    };
    "code-point-at-1.0.0" = {
      name = "code-point-at";
      packageName = "code-point-at";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-point-at/-/code-point-at-1.0.0.tgz";
        sha1 = "f69b192d3f7d91e382e4b71bddb77878619ab0c6";
      };
    };
    "is-fullwidth-code-point-1.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz";
        sha1 = "ef9e31386f031a7f0d643af82fde50c457ef00cb";
      };
    };
    "mute-stream-0.0.5" = {
      name = "mute-stream";
      packageName = "mute-stream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.5.tgz";
        sha1 = "8fbfabb0a98a253d3184331f9e8deb7372fac6c0";
      };
    };
    "number-is-nan-1.0.0" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.0.tgz";
        sha1 = "c020f529c5282adfdd233d91d4b181c3d686dc4b";
      };
    };
    "generate-function-2.0.0" = {
      name = "generate-function";
      packageName = "generate-function";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-function/-/generate-function-2.0.0.tgz";
        sha1 = "6858fe7c0969b7d4e9093337647ac79f60dfbe74";
      };
    };
    "generate-object-property-1.2.0" = {
      name = "generate-object-property";
      packageName = "generate-object-property";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-object-property/-/generate-object-property-1.2.0.tgz";
        sha1 = "9c0e1c40308ce804f4783618b937fa88f99d50d0";
      };
    };
    "jsonpointer-2.0.0" = {
      name = "jsonpointer";
      packageName = "jsonpointer";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonpointer/-/jsonpointer-2.0.0.tgz";
        sha1 = "3af1dd20fe85463910d469a385e33017d2a030d9";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "is-property-1.0.2" = {
      name = "is-property";
      packageName = "is-property";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-property/-/is-property-1.0.2.tgz";
        sha1 = "57fe1c4e48474edd65b09911f26b1cd4095dda84";
      };
    };
    "tryit-1.0.2" = {
      name = "tryit";
      packageName = "tryit";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tryit/-/tryit-1.0.2.tgz";
        sha1 = "c196b0073e6b1c595d93c9c830855b7acc32a453";
      };
    };
    "argparse-1.0.7" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.7.tgz";
        sha1 = "c289506480557810f14a8bc62d7a06f63ed7f951";
      };
    };
    "esprima-2.7.3" = {
      name = "esprima";
      packageName = "esprima";
      version = "2.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-2.7.3.tgz";
        sha1 = "96e3b70d5779f6ad49cd032673d1c312767ba581";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "jsonify-0.0.0" = {
      name = "jsonify";
      packageName = "jsonify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonify/-/jsonify-0.0.0.tgz";
        sha1 = "2c74b6ee41d93ca51b7b5aaee8f503631d252a73";
      };
    };
    "prelude-ls-1.1.2" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz";
        sha1 = "21932a549f5e52ffd9a827f570e04be62a97da54";
      };
    };
    "type-check-0.3.2" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.3.2.tgz";
        sha1 = "5884cab512cf1d355e3fb784f30804b2b520db72";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "deep-is-0.1.3" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.3.tgz";
        sha1 = "b369d6fb5dbc13eecf524f91b070feedc357cf34";
      };
    };
    "wordwrap-1.0.0" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-1.0.0.tgz";
        sha1 = "27584810891456a4171c8d0226441ade90cbcaeb";
      };
    };
    "fast-levenshtein-1.1.4" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-1.1.4.tgz";
        sha1 = "e6a754cc8f15e58987aa9cbd27af66fd6f4e5af9";
      };
    };
    "caller-path-0.1.0" = {
      name = "caller-path";
      packageName = "caller-path";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caller-path/-/caller-path-0.1.0.tgz";
        sha1 = "94085ef63581ecd3daa92444a8fe94e82577751f";
      };
    };
    "resolve-from-1.0.1" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-1.0.1.tgz";
        sha1 = "26cbfe935d1aeeeabb29bc3fe5aeb01e93d44226";
      };
    };
    "callsites-0.2.0" = {
      name = "callsites";
      packageName = "callsites";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callsites/-/callsites-0.2.0.tgz";
        sha1 = "afab96262910a7f33c19a5775825c69f34e350ca";
      };
    };
    "bluebird-3.4.3" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.4.3.tgz";
        sha1 = "1bdf56bb9336f4206f0f4efb7bedd5b5e9392058";
      };
    };
    "slice-ansi-0.0.4" = {
      name = "slice-ansi";
      packageName = "slice-ansi";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/slice-ansi/-/slice-ansi-0.0.4.tgz";
        sha1 = "edbf8903f66f7ce2f8eafd6ceed65e264c831b35";
      };
    };
    "tv4-1.2.7" = {
      name = "tv4";
      packageName = "tv4";
      version = "1.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/tv4/-/tv4-1.2.7.tgz";
        sha1 = "bd29389afc73ade49ae5f48142b5d544bf68d120";
      };
    };
    "xregexp-3.1.1" = {
      name = "xregexp";
      packageName = "xregexp";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xregexp/-/xregexp-3.1.1.tgz";
        sha1 = "8ee18d75ef5c7cb3f9967f8d29414a6ca5b1a184";
      };
    };
    "os-homedir-1.0.1" = {
      name = "os-homedir";
      packageName = "os-homedir";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-homedir/-/os-homedir-1.0.1.tgz";
        sha1 = "0d62bdf44b916fd3bbdcf2cab191948fb094f007";
      };
    };
    "jsx-ast-utils-1.3.1" = {
      name = "jsx-ast-utils";
      packageName = "jsx-ast-utils";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsx-ast-utils/-/jsx-ast-utils-1.3.1.tgz";
        sha1 = "14313c5c50da5b0c47020af5d1560c17e781a05a";
      };
    };
    "eslint-3.4.0" = {
      name = "eslint";
      packageName = "eslint";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint/-/eslint-3.4.0.tgz";
        sha1 = "af5984007bd3f1fb1b3b6b01a0a22eda0ec7a9f4";
      };
    };
    "babel-traverse-6.14.0" = {
      name = "babel-traverse";
      packageName = "babel-traverse";
      version = "6.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-traverse/-/babel-traverse-6.14.0.tgz";
        sha1 = "8d6bbf6273fc98ebc7eb9a222e9fb5260e9efab2";
      };
    };
    "babel-types-6.14.0" = {
      name = "babel-types";
      packageName = "babel-types";
      version = "6.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-types/-/babel-types-6.14.0.tgz";
        sha1 = "4c9b7047fa7d316040fbf0fa21203cf240dd7227";
      };
    };
    "babylon-6.9.1" = {
      name = "babylon";
      packageName = "babylon";
      version = "6.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/babylon/-/babylon-6.9.1.tgz";
        sha1 = "b839f39009bfdb5d20e37677b1b7802c59fe32ee";
      };
    };
    "lodash.assign-4.2.0" = {
      name = "lodash.assign";
      packageName = "lodash.assign";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.assign/-/lodash.assign-4.2.0.tgz";
        sha1 = "0d99f3ccd7a6d261d19bdaeb9245005d285808e7";
      };
    };
    "lodash.pickby-4.6.0" = {
      name = "lodash.pickby";
      packageName = "lodash.pickby";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.pickby/-/lodash.pickby-4.6.0.tgz";
        sha1 = "7dea21d8c18d7703a27c704c15d3b84a67e33aff";
      };
    };
    "babel-code-frame-6.11.0" = {
      name = "babel-code-frame";
      packageName = "babel-code-frame";
      version = "6.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-code-frame/-/babel-code-frame-6.11.0.tgz";
        sha1 = "9072dd2353fb0f85b6b57d2c97f0d134d188aed8";
      };
    };
    "babel-messages-6.8.0" = {
      name = "babel-messages";
      packageName = "babel-messages";
      version = "6.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-messages/-/babel-messages-6.8.0.tgz";
        sha1 = "bf504736ca967e6d65ef0adb5a2a5f947c8e0eb9";
      };
    };
    "babel-runtime-6.11.6" = {
      name = "babel-runtime";
      packageName = "babel-runtime";
      version = "6.11.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-runtime/-/babel-runtime-6.11.6.tgz";
        sha1 = "6db707fef2d49c49bfa3cb64efdb436b518b8222";
      };
    };
    "globals-8.18.0" = {
      name = "globals";
      packageName = "globals";
      version = "8.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globals/-/globals-8.18.0.tgz";
        sha1 = "93d4a62bdcac38cfafafc47d6b034768cb0ffcb4";
      };
    };
    "invariant-2.2.1" = {
      name = "invariant";
      packageName = "invariant";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/invariant/-/invariant-2.2.1.tgz";
        sha1 = "b097010547668c7e337028ebe816ebe36c8a8d54";
      };
    };
    "js-tokens-2.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-2.0.0.tgz";
        sha1 = "79903f5563ee778cc1162e6dcf1a0027c97f9cb5";
      };
    };
    "core-js-2.4.1" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.4.1.tgz";
        sha1 = "4de911e667b0eae9124e34254b53aea6fc618d3e";
      };
    };
    "regenerator-runtime-0.9.5" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.9.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.9.5.tgz";
        sha1 = "403d6d40a4bdff9c330dd9392dcbb2d9a8bba1fc";
      };
    };
    "loose-envify-1.2.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.2.0.tgz";
        sha1 = "69a65aad3de542cf4ee0f4fe74e8e33c709ccb0f";
      };
    };
    "js-tokens-1.0.3" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-1.0.3.tgz";
        sha1 = "14e56eb68c8f1a92c43d59f5014ec29dc20f2ae1";
      };
    };
    "to-fast-properties-1.0.2" = {
      name = "to-fast-properties";
      packageName = "to-fast-properties";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-fast-properties/-/to-fast-properties-1.0.2.tgz";
        sha1 = "f3f5c0c3ba7299a7ef99427e44633257ade43320";
      };
    };
  };
in
{
  eslint = nodeEnv.buildNodePackage {
    name = "eslint";
    packageName = "eslint";
    version = "3.4.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/eslint/-/eslint-3.4.0.tgz";
      sha1 = "af5984007bd3f1fb1b3b6b01a0a22eda0ec7a9f4";
    };
    dependencies = [
      (sources."chalk-1.1.3" // {
        dependencies = [
          sources."ansi-styles-2.2.1"
          sources."escape-string-regexp-1.0.5"
          (sources."has-ansi-2.0.0" // {
            dependencies = [
              sources."ansi-regex-2.0.0"
            ];
          })
          (sources."strip-ansi-3.0.1" // {
            dependencies = [
              sources."ansi-regex-2.0.0"
            ];
          })
          sources."supports-color-2.0.0"
        ];
      })
      (sources."concat-stream-1.5.1" // {
        dependencies = [
          sources."inherits-2.0.1"
          sources."typedarray-0.0.6"
          (sources."readable-stream-2.0.6" // {
            dependencies = [
              sources."core-util-is-1.0.2"
              sources."isarray-1.0.0"
              sources."process-nextick-args-1.0.7"
              sources."string_decoder-0.10.31"
              sources."util-deprecate-1.0.2"
            ];
          })
        ];
      })
      (sources."debug-2.2.0" // {
        dependencies = [
          sources."ms-0.7.1"
        ];
      })
      (sources."doctrine-1.3.0" // {
        dependencies = [
          sources."isarray-1.0.0"
        ];
      })
      (sources."escope-3.6.0" // {
        dependencies = [
          (sources."es6-map-0.1.4" // {
            dependencies = [
              sources."d-0.1.1"
              sources."es5-ext-0.10.12"
              sources."es6-iterator-2.0.0"
              sources."es6-set-0.1.4"
              sources."es6-symbol-3.1.0"
              sources."event-emitter-0.3.4"
            ];
          })
          (sources."es6-weak-map-2.0.1" // {
            dependencies = [
              sources."d-0.1.1"
              sources."es5-ext-0.10.12"
              sources."es6-iterator-2.0.0"
              sources."es6-symbol-3.1.0"
            ];
          })
          (sources."esrecurse-4.1.0" // {
            dependencies = [
              sources."estraverse-4.1.1"
              sources."object-assign-4.1.0"
            ];
          })
        ];
      })
      (sources."espree-3.1.7" // {
        dependencies = [
          sources."acorn-3.3.0"
          sources."acorn-jsx-3.0.1"
        ];
      })
      sources."estraverse-4.2.0"
      sources."esutils-2.0.2"
      (sources."file-entry-cache-2.0.0" // {
        dependencies = [
          (sources."flat-cache-1.2.1" // {
            dependencies = [
              sources."circular-json-0.3.1"
              (sources."del-2.2.2" // {
                dependencies = [
                  (sources."globby-5.0.0" // {
                    dependencies = [
                      (sources."array-union-1.0.2" // {
                        dependencies = [
                          sources."array-uniq-1.0.3"
                        ];
                      })
                      sources."arrify-1.0.1"
                    ];
                  })
                  sources."is-path-cwd-1.0.0"
                  (sources."is-path-in-cwd-1.0.0" // {
                    dependencies = [
                      sources."is-path-inside-1.0.0"
                    ];
                  })
                  sources."pify-2.3.0"
                  (sources."pinkie-promise-2.0.1" // {
                    dependencies = [
                      sources."pinkie-2.0.4"
                    ];
                  })
                  sources."rimraf-2.5.4"
                ];
              })
              sources."graceful-fs-4.1.6"
              sources."write-0.2.1"
            ];
          })
          sources."object-assign-4.1.0"
        ];
      })
      (sources."glob-7.0.6" // {
        dependencies = [
          sources."fs.realpath-1.0.0"
          (sources."inflight-1.0.5" // {
            dependencies = [
              sources."wrappy-1.0.2"
            ];
          })
          sources."inherits-2.0.1"
          (sources."minimatch-3.0.3" // {
            dependencies = [
              (sources."brace-expansion-1.1.6" // {
                dependencies = [
                  sources."balanced-match-0.4.2"
                  sources."concat-map-0.0.1"
                ];
              })
            ];
          })
          (sources."once-1.3.3" // {
            dependencies = [
              sources."wrappy-1.0.2"
            ];
          })
          sources."path-is-absolute-1.0.0"
        ];
      })
      sources."globals-9.9.0"
      sources."ignore-3.1.5"
      sources."imurmurhash-0.1.4"
      (sources."inquirer-0.12.0" // {
        dependencies = [
          sources."ansi-escapes-1.4.0"
          sources."ansi-regex-2.0.0"
          (sources."cli-cursor-1.0.2" // {
            dependencies = [
              (sources."restore-cursor-1.0.1" // {
                dependencies = [
                  sources."exit-hook-1.1.1"
                  sources."onetime-1.1.0"
                ];
              })
            ];
          })
          sources."cli-width-2.1.0"
          (sources."figures-1.7.0" // {
            dependencies = [
              sources."escape-string-regexp-1.0.5"
              sources."object-assign-4.1.0"
            ];
          })
          (sources."readline2-1.0.1" // {
            dependencies = [
              (sources."code-point-at-1.0.0" // {
                dependencies = [
                  sources."number-is-nan-1.0.0"
                ];
              })
              (sources."is-fullwidth-code-point-1.0.0" // {
                dependencies = [
                  sources."number-is-nan-1.0.0"
                ];
              })
              sources."mute-stream-0.0.5"
            ];
          })
          (sources."run-async-0.1.0" // {
            dependencies = [
              (sources."once-1.3.3" // {
                dependencies = [
                  sources."wrappy-1.0.2"
                ];
              })
            ];
          })
          sources."rx-lite-3.1.2"
          (sources."string-width-1.0.2" // {
            dependencies = [
              (sources."code-point-at-1.0.0" // {
                dependencies = [
                  sources."number-is-nan-1.0.0"
                ];
              })
              (sources."is-fullwidth-code-point-1.0.0" // {
                dependencies = [
                  sources."number-is-nan-1.0.0"
                ];
              })
            ];
          })
          sources."strip-ansi-3.0.1"
          sources."through-2.3.8"
        ];
      })
      (sources."is-my-json-valid-2.13.1" // {
        dependencies = [
          sources."generate-function-2.0.0"
          (sources."generate-object-property-1.2.0" // {
            dependencies = [
              sources."is-property-1.0.2"
            ];
          })
          sources."jsonpointer-2.0.0"
          sources."xtend-4.0.1"
        ];
      })
      (sources."is-resolvable-1.0.0" // {
        dependencies = [
          sources."tryit-1.0.2"
        ];
      })
      (sources."js-yaml-3.6.1" // {
        dependencies = [
          (sources."argparse-1.0.7" // {
            dependencies = [
              sources."sprintf-js-1.0.3"
            ];
          })
          sources."esprima-2.7.3"
        ];
      })
      (sources."json-stable-stringify-1.0.1" // {
        dependencies = [
          sources."jsonify-0.0.0"
        ];
      })
      (sources."levn-0.3.0" // {
        dependencies = [
          sources."prelude-ls-1.1.2"
          sources."type-check-0.3.2"
        ];
      })
      sources."lodash-4.15.0"
      (sources."mkdirp-0.5.1" // {
        dependencies = [
          sources."minimist-0.0.8"
        ];
      })
      sources."natural-compare-1.4.0"
      (sources."optionator-0.8.1" // {
        dependencies = [
          sources."prelude-ls-1.1.2"
          sources."deep-is-0.1.3"
          sources."wordwrap-1.0.0"
          sources."type-check-0.3.2"
          sources."fast-levenshtein-1.1.4"
        ];
      })
      sources."path-is-inside-1.0.1"
      sources."pluralize-1.2.1"
      sources."progress-1.1.8"
      (sources."require-uncached-1.0.2" // {
        dependencies = [
          (sources."caller-path-0.1.0" // {
            dependencies = [
              sources."callsites-0.2.0"
            ];
          })
          sources."resolve-from-1.0.1"
        ];
      })
      sources."shelljs-0.6.1"
      sources."strip-bom-3.0.0"
      sources."strip-json-comments-1.0.4"
      (sources."table-3.7.8" // {
        dependencies = [
          sources."bluebird-3.4.3"
          sources."slice-ansi-0.0.4"
          (sources."string-width-1.0.2" // {
            dependencies = [
              (sources."code-point-at-1.0.0" // {
                dependencies = [
                  sources."number-is-nan-1.0.0"
                ];
              })
              (sources."is-fullwidth-code-point-1.0.0" // {
                dependencies = [
                  sources."number-is-nan-1.0.0"
                ];
              })
            ];
          })
          (sources."strip-ansi-3.0.1" // {
            dependencies = [
              sources."ansi-regex-2.0.0"
            ];
          })
          sources."tv4-1.2.7"
          sources."xregexp-3.1.1"
        ];
      })
      sources."text-table-0.2.0"
      (sources."user-home-2.0.0" // {
        dependencies = [
          sources."os-homedir-1.0.1"
        ];
      })
    ];
    meta = {
      description = "An AST-based pattern checker for JavaScript.";
      homepage = http://eslint.org/;
      license = "MIT";
    };
    production = true;
  };
  eslint-plugin-react = nodeEnv.buildNodePackage {
    name = "eslint-plugin-react";
    packageName = "eslint-plugin-react";
    version = "6.1.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/eslint-plugin-react/-/eslint-plugin-react-6.1.2.tgz";
      sha1 = "d6022bd9bce448e517a003abc6409e7ca1800c68";
    };
    dependencies = [
      (sources."doctrine-1.3.0" // {
        dependencies = [
          sources."esutils-2.0.2"
          sources."isarray-1.0.0"
        ];
      })
      (sources."jsx-ast-utils-1.3.1" // {
        dependencies = [
          sources."object-assign-4.1.0"
        ];
      })
      (sources."eslint-3.4.0" // {
        dependencies = [
          (sources."chalk-1.1.3" // {
            dependencies = [
              sources."ansi-styles-2.2.1"
              sources."escape-string-regexp-1.0.5"
              (sources."has-ansi-2.0.0" // {
                dependencies = [
                  sources."ansi-regex-2.0.0"
                ];
              })
              (sources."strip-ansi-3.0.1" // {
                dependencies = [
                  sources."ansi-regex-2.0.0"
                ];
              })
              sources."supports-color-2.0.0"
            ];
          })
          (sources."concat-stream-1.5.1" // {
            dependencies = [
              sources."inherits-2.0.1"
              sources."typedarray-0.0.6"
              (sources."readable-stream-2.0.6" // {
                dependencies = [
                  sources."core-util-is-1.0.2"
                  sources."isarray-1.0.0"
                  sources."process-nextick-args-1.0.7"
                  sources."string_decoder-0.10.31"
                  sources."util-deprecate-1.0.2"
                ];
              })
            ];
          })
          (sources."debug-2.2.0" // {
            dependencies = [
              sources."ms-0.7.1"
            ];
          })
          (sources."escope-3.6.0" // {
            dependencies = [
              (sources."es6-map-0.1.4" // {
                dependencies = [
                  sources."d-0.1.1"
                  sources."es5-ext-0.10.12"
                  sources."es6-iterator-2.0.0"
                  sources."es6-set-0.1.4"
                  sources."es6-symbol-3.1.0"
                  sources."event-emitter-0.3.4"
                ];
              })
              (sources."es6-weak-map-2.0.1" // {
                dependencies = [
                  sources."d-0.1.1"
                  sources."es5-ext-0.10.12"
                  sources."es6-iterator-2.0.0"
                  sources."es6-symbol-3.1.0"
                ];
              })
              (sources."esrecurse-4.1.0" // {
                dependencies = [
                  sources."estraverse-4.1.1"
                  sources."object-assign-4.1.0"
                ];
              })
            ];
          })
          (sources."espree-3.1.7" // {
            dependencies = [
              sources."acorn-3.3.0"
              sources."acorn-jsx-3.0.1"
            ];
          })
          sources."estraverse-4.2.0"
          sources."esutils-2.0.2"
          (sources."file-entry-cache-2.0.0" // {
            dependencies = [
              (sources."flat-cache-1.2.1" // {
                dependencies = [
                  sources."circular-json-0.3.1"
                  (sources."del-2.2.2" // {
                    dependencies = [
                      (sources."globby-5.0.0" // {
                        dependencies = [
                          (sources."array-union-1.0.2" // {
                            dependencies = [
                              sources."array-uniq-1.0.3"
                            ];
                          })
                          sources."arrify-1.0.1"
                        ];
                      })
                      sources."is-path-cwd-1.0.0"
                      (sources."is-path-in-cwd-1.0.0" // {
                        dependencies = [
                          sources."is-path-inside-1.0.0"
                        ];
                      })
                      sources."pify-2.3.0"
                      (sources."pinkie-promise-2.0.1" // {
                        dependencies = [
                          sources."pinkie-2.0.4"
                        ];
                      })
                      sources."rimraf-2.5.4"
                    ];
                  })
                  sources."graceful-fs-4.1.6"
                  sources."write-0.2.1"
                ];
              })
              sources."object-assign-4.1.0"
            ];
          })
          (sources."glob-7.0.6" // {
            dependencies = [
              sources."fs.realpath-1.0.0"
              (sources."inflight-1.0.5" // {
                dependencies = [
                  sources."wrappy-1.0.2"
                ];
              })
              sources."inherits-2.0.1"
              (sources."minimatch-3.0.3" // {
                dependencies = [
                  (sources."brace-expansion-1.1.6" // {
                    dependencies = [
                      sources."balanced-match-0.4.2"
                      sources."concat-map-0.0.1"
                    ];
                  })
                ];
              })
              (sources."once-1.3.3" // {
                dependencies = [
                  sources."wrappy-1.0.2"
                ];
              })
              sources."path-is-absolute-1.0.0"
            ];
          })
          sources."globals-9.9.0"
          sources."ignore-3.1.5"
          sources."imurmurhash-0.1.4"
          (sources."inquirer-0.12.0" // {
            dependencies = [
              sources."ansi-escapes-1.4.0"
              sources."ansi-regex-2.0.0"
              (sources."cli-cursor-1.0.2" // {
                dependencies = [
                  (sources."restore-cursor-1.0.1" // {
                    dependencies = [
                      sources."exit-hook-1.1.1"
                      sources."onetime-1.1.0"
                    ];
                  })
                ];
              })
              sources."cli-width-2.1.0"
              (sources."figures-1.7.0" // {
                dependencies = [
                  sources."escape-string-regexp-1.0.5"
                  sources."object-assign-4.1.0"
                ];
              })
              (sources."readline2-1.0.1" // {
                dependencies = [
                  (sources."code-point-at-1.0.0" // {
                    dependencies = [
                      sources."number-is-nan-1.0.0"
                    ];
                  })
                  (sources."is-fullwidth-code-point-1.0.0" // {
                    dependencies = [
                      sources."number-is-nan-1.0.0"
                    ];
                  })
                  sources."mute-stream-0.0.5"
                ];
              })
              (sources."run-async-0.1.0" // {
                dependencies = [
                  (sources."once-1.3.3" // {
                    dependencies = [
                      sources."wrappy-1.0.2"
                    ];
                  })
                ];
              })
              sources."rx-lite-3.1.2"
              (sources."string-width-1.0.2" // {
                dependencies = [
                  (sources."code-point-at-1.0.0" // {
                    dependencies = [
                      sources."number-is-nan-1.0.0"
                    ];
                  })
                  (sources."is-fullwidth-code-point-1.0.0" // {
                    dependencies = [
                      sources."number-is-nan-1.0.0"
                    ];
                  })
                ];
              })
              sources."strip-ansi-3.0.1"
              sources."through-2.3.8"
            ];
          })
          (sources."is-my-json-valid-2.13.1" // {
            dependencies = [
              sources."generate-function-2.0.0"
              (sources."generate-object-property-1.2.0" // {
                dependencies = [
                  sources."is-property-1.0.2"
                ];
              })
              sources."jsonpointer-2.0.0"
              sources."xtend-4.0.1"
            ];
          })
          (sources."is-resolvable-1.0.0" // {
            dependencies = [
              sources."tryit-1.0.2"
            ];
          })
          (sources."js-yaml-3.6.1" // {
            dependencies = [
              (sources."argparse-1.0.7" // {
                dependencies = [
                  sources."sprintf-js-1.0.3"
                ];
              })
              sources."esprima-2.7.3"
            ];
          })
          (sources."json-stable-stringify-1.0.1" // {
            dependencies = [
              sources."jsonify-0.0.0"
            ];
          })
          (sources."levn-0.3.0" // {
            dependencies = [
              sources."prelude-ls-1.1.2"
              sources."type-check-0.3.2"
            ];
          })
          sources."lodash-4.15.0"
          (sources."mkdirp-0.5.1" // {
            dependencies = [
              sources."minimist-0.0.8"
            ];
          })
          sources."natural-compare-1.4.0"
          (sources."optionator-0.8.1" // {
            dependencies = [
              sources."prelude-ls-1.1.2"
              sources."deep-is-0.1.3"
              sources."wordwrap-1.0.0"
              sources."type-check-0.3.2"
              sources."fast-levenshtein-1.1.4"
            ];
          })
          sources."path-is-inside-1.0.1"
          sources."pluralize-1.2.1"
          sources."progress-1.1.8"
          (sources."require-uncached-1.0.2" // {
            dependencies = [
              (sources."caller-path-0.1.0" // {
                dependencies = [
                  sources."callsites-0.2.0"
                ];
              })
              sources."resolve-from-1.0.1"
            ];
          })
          sources."shelljs-0.6.1"
          sources."strip-bom-3.0.0"
          sources."strip-json-comments-1.0.4"
          (sources."table-3.7.8" // {
            dependencies = [
              sources."bluebird-3.4.3"
              sources."slice-ansi-0.0.4"
              (sources."string-width-1.0.2" // {
                dependencies = [
                  (sources."code-point-at-1.0.0" // {
                    dependencies = [
                      sources."number-is-nan-1.0.0"
                    ];
                  })
                  (sources."is-fullwidth-code-point-1.0.0" // {
                    dependencies = [
                      sources."number-is-nan-1.0.0"
                    ];
                  })
                ];
              })
              (sources."strip-ansi-3.0.1" // {
                dependencies = [
                  sources."ansi-regex-2.0.0"
                ];
              })
              sources."tv4-1.2.7"
              sources."xregexp-3.1.1"
            ];
          })
          sources."text-table-0.2.0"
          (sources."user-home-2.0.0" // {
            dependencies = [
              sources."os-homedir-1.0.1"
            ];
          })
        ];
      })
    ];
    meta = {
      description = "React specific linting rules for ESLint";
      homepage = https://github.com/yannickcr/eslint-plugin-react;
      license = "MIT";
    };
    production = true;
  };
  babel-eslint = nodeEnv.buildNodePackage {
    name = "babel-eslint";
    packageName = "babel-eslint";
    version = "6.1.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/babel-eslint/-/babel-eslint-6.1.2.tgz";
      sha1 = "5293419fe3672d66598d327da9694567ba6a5f2f";
    };
    dependencies = [
      (sources."babel-traverse-6.14.0" // {
        dependencies = [
          (sources."babel-code-frame-6.11.0" // {
            dependencies = [
              (sources."chalk-1.1.3" // {
                dependencies = [
                  sources."ansi-styles-2.2.1"
                  sources."escape-string-regexp-1.0.5"
                  (sources."has-ansi-2.0.0" // {
                    dependencies = [
                      sources."ansi-regex-2.0.0"
                    ];
                  })
                  (sources."strip-ansi-3.0.1" // {
                    dependencies = [
                      sources."ansi-regex-2.0.0"
                    ];
                  })
                  sources."supports-color-2.0.0"
                ];
              })
              sources."esutils-2.0.2"
              sources."js-tokens-2.0.0"
            ];
          })
          sources."babel-messages-6.8.0"
          (sources."babel-runtime-6.11.6" // {
            dependencies = [
              sources."core-js-2.4.1"
              sources."regenerator-runtime-0.9.5"
            ];
          })
          (sources."debug-2.2.0" // {
            dependencies = [
              sources."ms-0.7.1"
            ];
          })
          sources."globals-8.18.0"
          (sources."invariant-2.2.1" // {
            dependencies = [
              (sources."loose-envify-1.2.0" // {
                dependencies = [
                  sources."js-tokens-1.0.3"
                ];
              })
            ];
          })
          sources."lodash-4.15.0"
        ];
      })
      (sources."babel-types-6.14.0" // {
        dependencies = [
          (sources."babel-runtime-6.11.6" // {
            dependencies = [
              sources."core-js-2.4.1"
              sources."regenerator-runtime-0.9.5"
            ];
          })
          sources."esutils-2.0.2"
          sources."lodash-4.15.0"
          sources."to-fast-properties-1.0.2"
        ];
      })
      (sources."babylon-6.9.1" // {
        dependencies = [
          (sources."babel-runtime-6.11.6" // {
            dependencies = [
              sources."core-js-2.4.1"
              sources."regenerator-runtime-0.9.5"
            ];
          })
        ];
      })
      sources."lodash.assign-4.2.0"
      sources."lodash.pickby-4.6.0"
    ];
    meta = {
      description = "Custom parser for ESLint";
      homepage = https://github.com/babel/babel-eslint;
      license = "MIT";
    };
    production = true;
  };
}