# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "gometalinter-${version}";
  version = "20161124-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "1df416899120d87ae62df60322721e5516615afb";

  goPackagePath = "github.com/alecthomas/gometalinter";
  subPackages = [ "." ];

  src = fetchgit {
    inherit rev;
    url = "https://github.com/alecthomas/gometalinter";
    sha256 = "1wacf0z9kcch6jbnykddcjp6a8wcvqf394x72hrzwgaq3hjapwww";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
