# This file was generated by go2nix.
[
  {
    goPackagePath = "github.com/alecthomas/template";
    fetch = {
      type = "git";
      url = "https://github.com/alecthomas/template";
      rev = "a0175ee3bccc567396460bf5acd36800cb10c49c";
      sha256 = "0qjgvvh26vk1cyfq9fadyhfgdj36f1iapbmr5xp6zqipldz8ffxj";
    };
  }
  {
    goPackagePath = "github.com/alecthomas/units";
    fetch = {
      type = "git";
      url = "https://github.com/alecthomas/units";
      rev = "2efee857e7cfd4f3d0138cc3cbb1b4966962b93a";
      sha256 = "1j65b91qb9sbrml9cpabfrcf07wmgzzghrl7809hjjhrmbzri5bl";
    };
  }
  {
    goPackagePath = "github.com/google/shlex";
    fetch = {
      type = "git";
      url = "https://github.com/google/shlex";
      rev = "6f45313302b9c56850fc17f99e40caebce98c716";
      sha256 = "0ybz1w3hndma8myq3pxan36533hy9f4w598hsv4hnj21l4br8jpx";
    };
  }
  {
    goPackagePath = "gopkg.in/alecthomas/kingpin.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/alecthomas/kingpin.v2";
      rev = "e9044be3ab2a8e11d4e1f418d12f0790d57e8d70";
      sha256 = "1kzk1ylii9aqip0ss4zc2zxwa16lr5j3p3bgyjr276rig68i68ji";
    };
  }
]
